### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by UjGamer** [UjGamer/scet#1]
2.0 Release todo:
- [ ] `scet-asym`  for encrypting small pieces of data using raw asymmetric algorithms.
- [ ] `scet-seal` for encrypting large amounts of data using symmetric algorithm with key, encrypted using asymmetric algorithm.
- [ ] Extend `scet-benchmark` to allow benchmarking asymmetric algorithms.
- [ ] `scet-key` asymmetric key generator.
- [ ] `scet-hash` unifed hash-functions digests generator.
  
- [x] Separate executable `scet-benchmark` for perfomance testing (4248aa6f2602cb1543652f021e7b4e3ad49d8896, a43821831fd994d6879b9a3ff9fcaec01cb64d05).
- [x] Erase memory when signal is received (2dbd4b3bb7011e442defd4939c88efe7ef3c46f7).

Repository maintenance:
- [ ] Stop pushing non-tested code into `master` branch.
- [ ] Cover code with regressions tests to make sure compatability kept between minor and patch version changes.
- [x] Get rid of submodules (138a7e0a58172100abcf2f7177f85ddd61a3ecda, edb069ff186eda228763d7272e41bbf6fce171b2, 6dff2c3b84216049831f854f8d9fa41a54f159a7).
- [x] Allow building outside of Git repository (7211bf0c86bc008698daab26686eda1a5a8443a).

_Currently i'm busy with school and can't actively develop scet suite._

**Comment by UjGamer** [comment]
Not used.
